### ISSUE TITLE
Use with jetstream

### ISSUE THREAD

**Issue by vanthao03596** [Nothing-Works/vuetifyjs-mix-extension#18]
Hi i'm try to use vuetify with jetstream. I tried your extension but when apply .vuetify('vuetify-loader') some css from tailwind will not work. Is there anyway to fix this ?
My webpack.mix.js
```
const mix = require('laravel-mix');
require('vuetifyjs-mix-extension');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .vuetify('vuetify-loader')
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ])
    .webpackConfig(require('./webpack.config'));

if (mix.inProduction()) {
    mix.version();
}

```
Dep
```
 "devDependencies": {
        "@inertiajs/inertia": "^0.8.2",
        "@inertiajs/inertia-vue": "^0.5.4",
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.0",
        "autoprefixer": "^9.8.6",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "portal-vue": "^2.1.7",
        "postcss-import": "^12.0.1",
        "resolve-url-loader": "^3.1.0",
        "sass": "^1.32.0",
        "sass-loader": "^9.0.0",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10",
        "vuetify-loader": "^1.6.0",
        "vuetifyjs-mix-extension": "^0.0.17"
    },
    "dependencies": {
        "vuetify": "^2.4.0"
    }
```

Screen error
![1](https://user-images.githubusercontent.com/34786441/103358774-f9474e00-4ae8-11eb-8c74-42d8fb7f7194.png)

**Comment by Nothing-Works** [comment]
So basically you are using two `css` frameworks together, I have not tried your setup but I am guessing it's something related to `css` class names collisions. I will try this when I have time.

**Comment by Davit-000** [comment]
### When using 'vuetify-loader' webpack-cli Throws Error

**webpack.mix.js**
`
const mix = require('laravel-mix');
require('vuetifyjs-mix-extension');


mix
  .ts('resources/ts/app.ts', 'public/js')
  .vue({
    version: 2,
    extractStyles: true
  })
  .sass('resources/sass/app.sass', 'public/css', {
    implementation: require('sass'),
    sassOptions: {
      indentWidth: 4,
      indentedSyntax: true
    },
  })
  .options({
    processCssUrls: true
  })
  .webpackConfig(require('./webpack.config'))
  .vuetify('vuetify-loader')

if (mix.inProduction()) {
  mix.version();
}
`
**packaje.json**

`
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "mix",
    "hot": "mix watch --hot",
    "prod": "npm run production",
    "production": "mix --production",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000"
  },
  "dependencies": {
    "@inertiajs/inertia": "^0.8.4",
    "@inertiajs/inertia-vue": "^0.5.5",
    "@mdi/font": "^5.9.55",
    "axios": "^0.21.1",
    "lodash": "^4.17.20",
    "vue": "^2.6.12",
    "vue-class-component": "^7.2.6",
    "vue-property-decorator": "^9.1.2",
    "vuetify": "^2.4.3",
    "ziggy-js": "^1.0.4"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.168",
    "@types/node": "^14.14.22",
    "@types/webpack-env": "^1.16.0",
    "@types/ziggy-js": "^0.9.0",
    "deepmerge": "^4.2.2",
    "laravel-mix": "^6.0.10",
    "resolve-url-loader": "^3.1.2",
    "sass": "^1.32.5",
    "sass-loader": "^10.1.1",
    "ts-loader": "^8.0.14",
    "typescript": "^4.1.3",
    "vue-loader": "^15.9.6",
    "vue-template-compiler": "^2.6.12",
    "vuetify-loader": "^1.6.0",
    "vuetifyjs-mix-extension": "0.0.18"
  }
}
`
**Error Stack**

`
[webpack-cli] Error: Cannot find module 'webpack/lib/RuleSet'
Require stack:
- C:\laragon\www\schedule\node_modules\vuetify-loader\lib\plugin.js
- C:\laragon\www\schedule\node_modules\vuetifyjs-mix-extension\index.js
- C:\laragon\www\schedule\webpack.mix.js
- C:\laragon\www\schedule\node_modules\laravel-mix\setup\webpack.config.js
- C:\laragon\www\schedule\node_modules\webpack-cli\lib\webpack-cli.js
- C:\laragon\www\schedule\node_modules\webpack-cli\lib\bootstrap.js
- C:\laragon\www\schedule\node_modules\webpack-cli\bin\cli.js
- C:\laragon\www\schedule\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\laragon\www\schedule\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\laragon\www\schedule\node_modules\vuetify-loader\lib\plugin.js:1:79)
    at Module._compile (C:\laragon\www\schedule\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (C:\laragon\www\schedule\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Vuetify.addVuetifyLoader (C:\laragon\www\schedule\node_modules\vuetifyjs-mix-extension\index.js:91:37)
    at Vuetify.webpackConfig (C:\laragon\www\schedule\node_modules\vuetifyjs-mix-extension\index.js:81:44)
    at C:\laragon\www\schedule\node_modules\laravel-mix\src\components\ComponentRegistrar.js:106:54
    at C:\laragon\www\schedule\node_modules\laravel-mix\src\Dispatcher.js:37:62
    at Array.map (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\laragon\\www\\schedule\\node_modules\\vuetify-loader\\lib\\plugin.js',
    'C:\\laragon\\www\\schedule\\node_modules\\vuetifyjs-mix-extension\\index.js',
    'C:\\laragon\\www\\schedule\\webpack.mix.js',
    'C:\\laragon\\www\\schedule\\node_modules\\laravel-mix\\setup\\webpack.config.js',
    'C:\\laragon\\www\\schedule\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\laragon\\www\\schedule\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\laragon\\www\\schedule\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\laragon\\www\\schedule\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
`
