### ISSUE TITLE
add support for SASS variables

### ISSUE THREAD

**Issue by Nothing-Works** [Nothing-Works/vuetifyjs-mix-extension#6]
Custom [SASS variables](https://vuetifyjs.com/en/customization/sass-variables/) file is not supported atm. This means importing your project's specific variables file is not working.

The only thing you can do is to import the default framework styles file:

This is the preferred method if you are using [Presets](https://vuetifyjs.com/en/customization/presets/) or **not** using a variables file at all.
```js
<style lang="sass">
  @import '~vuetify/src/styles/styles.sass'

  @media #{map-get($display-breakpoints, 'md-and-down')}
    .custom-class
      display: none
</style>
```

**Comment by Nothing-Works** [comment]
version 0.0.7 `npm i vuetifyjs-mix-extension@latest -D` should the problem.

**Comment by stephenjason89** [comment]
Thank you for update, I just saw this now and immediately tried it. However, i have an option

```
{   match(originalTag, {kebabTag, camelTag, path, component}) {
            if (kebabTag.startsWith('core-')) {
                return [camelTag, `import ${camelTag} from '@/components/core/${camelTag.substring(4)}.vue'`]
            }
        }
    }
```
npm is currently throwing me 
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by Nothing-Works** [comment]
@stephenjason89 this is very strange, I just tried your code, and I do not get this error. can you find which line of code cause this error?

**Comment by stephenjason89** [comment]
```
> npm run development


> @ development C:\Development\Web Projects\Timekeeper
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.resolve (path.js:139:9)
    at getPath (C:\Development\Web Projects\Timekeeper\node_modules\vuetifyjs-mix-extension\src\getPath.js:8:17)
    at new Vuetify (C:\Development\Web Projects\Timekeeper\node_modules\vuetifyjs-mix-extension\index.js:7:28)
    at Object.<anonymous> (C:\Development\Web Projects\Timekeeper\node_modules\vuetifyjs-mix-extension\index.js:81:23)
    at Module._compile (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Development\Web Projects\Timekeeper\webpack.mix.js:3:1)
    at Module._compile (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Development\Web Projects\Timekeeper\node_modules\laravel-mix\setup\webpack.config.js:12:1)
    at Module._compile (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (C:\Development\Web Projects\Timekeeper\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Development\Web Projects\Timekeeper\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}

```

Here's the error code.


here's my mix file for reference

```
const mix = require('laravel-mix');
const WorkerPlugin = require('worker-plugin');
require('vuetifyjs-mix-extension');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
    .js([ 
        'resources/js/proj/app.js',
    ], 'public/js/timekeeper').sourceMaps()

    .vuetify('vuetify-loader', {
        /**
         * This function will be called for every tag used in each vue component
         * It should return an array, the first element will be inserted into the
         * components array, the second should be a corresponding import
         *
         * originalTag - the tag as it was originally used in the template
         * kebabTag    - the tag normalised to kebab-case
         * camelTag    - the tag normalised to PascalCase
         * path        - a relative path to the current .vue file
         * component   - a parsed representation of the current component
         */
        match(originalTag, {kebabTag, camelTag, path, component}) {
            if (kebabTag.startsWith('core-')) {
                return [camelTag, `import ${camelTag} from '@/components/core/${camelTag.substring(4)}.vue'`]
            }
        }
    })

    .webpackConfig({
        resolve: {
            alias: {
                '@': path.resolve(__dirname, 'resources/js/')
            }
        },
        plugins: [
            new WorkerPlugin({
                filename: '[name].worker.js',
                globalObject: "(typeof self!='undefined'?self:global)"
            }),
        ],
    });

```

just did
npm i vuetifyjs-mix-extension@latest -D 
then npm run dev.

Thank you for helping :)

**Comment by Nothing-Works** [comment]
@stephenjason89  I think this is a windows path problem, I have modified some code which is `0.0.8`. However, I do not have a windows machine, can you help me to test it?

**Comment by stephenjason89** [comment]
@Nothing-Works Great job bro. It is compiling without errors now.
So i tested variables.scss if it is working
i placed it in the default path
resources/sass/variables.scss and used

```

$btn-sizes: (
    'default': 5,
    'large': 2
);

$headings: (
    'h1': (
        'size': 0.3125rem,
        'line-height': 1.15em
    ),
    'h2': (
        'size': 0.25rem,
        'line-height': 1.5em
    )
);
```

Placed an h1 tag on my template but it doesn't change the size
so i went back to mix and explicitly wrote
``
.vuetify('vuetify-loader', 'resources/sass/variables.scss',{options})
``

but still did not work.

:)

**Comment by Nothing-Works** [comment]
@stephenjason89  did you import the Vuetify styles?

**Comment by Nothing-Works** [comment]
@stephenjason89 The plugin works, you need to understand more `sass` and `vuetifyjs`. The problem is that `'h1'` under `$headings` does not mean that it's going apply to all `<h1>` tags. It corresponds to one of the classes in [Typograph](https://vuetifyjs.com/en/styles/typography/). So you need to add `display-4` class to your `h1`.

**Comment by stephenjason89** [comment]
Thank you for the reply. May i see a sample code of how i use the sass in a component?
This is my first time to use sass haha :D Just figuring out how to make it work.
I just need a few sample where i can change some things in the component using sass.
should i still import the var file or is it automatically imported as well?

**Comment by Nothing-Works** [comment]
@stephenjason89 the [vuetify doc](https://vuetifyjs.com/en/customization/sass-variables/) is a really good starting point.

**Comment by stephenjason89** [comment]
I see that the compilation time has gone up everytime i change something in the variables file.

```
@import '~vuetify/src/styles/styles.sass';

$btn-sizes: (
    'default': 150,
    'large': 200
);

$material-light: map-merge($material-light, ( cards: red));
$material-dark: map-merge($material-dark, ( cards: red));

```

here's what i'm trying to see if it will work or not.
Unfortunately i can't seem to see any changes in my components.

I don't know what i'm doing wrong

my <v-card> didn't turn to red nor my buttons didn't increase in size

I'm hoping you can shed some light thank you!

**Comment by Nothing-Works** [comment]
@stephenjason89 this is a working [repo](https://github.com/Nothing-Works/mix) for me.

**Comment by stephenjason89** [comment]
Thank you so much for the link.
By the way, i'm using Progressive images with sharp

```
progressiveImages: {
            size: 512, // Use higher-resolution previews
            sharp: true, // Use sharp instead of ImageMagick
        }
```
While everything works perfectly when online, it auto generates a low res placeholder,
but i'm using service workers to have an offline mode.

So i see all the images in my public/images directory with the correct file names but

```
The FetchEvent for "http://laravel.localhost/images/logo.jpg?8829841dd1308d7eb06e7e1eb245e448" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) @ upup.sw.min.js:35
The FetchEvent for "http://laravel.localhost/images/image2.jpg?485ac532e1577ea3631328e72414d803" resulted in a network error response: an object that was not a Response was passed to respondWith().
Promise.then (async)
(anonymous) @ upup.sw.min.js:35
The FetchEvent for "http://laravel.localhost/images/image1.jpg?41c6fdbf47e6d623274ea5a218e78d29" resulted in a network error response: an object that was not a Response was passed to respondWith().
```

it tries to fetch an image with a hash /image1.jpg?41c6fdbf47e6d623274ea5a218e78d29
can i disable that behavior?

**Comment by itelmenko** [comment]
Hello!

Please help. I can't redefine sass variables.

I have created resources/sass/filemanager/variables.scss with

```
$font-size-root: 14px;
```

In webpack.mix.js:

```
mix.js('resources/js/filemanager/main.js', 'public/js/filemanager')
	.vuetify('vuetify-loader', 'resources/sass/filemanager/variables.scss');
```

It builds fine (without any errors). But it does not change global style from vuetify settings
src/styles/settings/_variables.scss

```
$font-size-root: 16px !default;
```

which vutify uses here src/styles/elements/_global.sass
```
html
  font-size: $font-size-root
```

And as result I get default value:

```
html {
    font-size: 16px;
...
}
```

**Comment by Nothing-Works** [comment]
@itelmenko hi `https://github.com/Nothing-Works/mix` this is a sample repo which works for me, can you check it, please? let me know if there is anything I can help.

**Comment by CasperLaiTW** [comment]
@itelmenko make suer your `sass-loader >= 9.0`
